[paths]
EVE_JSON = suricata_out/eve.json
RULES_DIR = rules
BEHAVIOR_MODEL = ./models/ids_stage1_user_behavior.joblib
NET_MODEL = ./models/ids_stage1_binary.joblib
BEH_MODEL = ./models/ids_stage1_user_behavior.joblib
stage2_bundle = ./models/ids_stage2_multiclass.joblib
MODEL_SQLI     = ./models/sql_inject/sqli_dl_model.h5
SCALER_SQLI    = ./models/sql_inject/scaler.joblib
TOKENIZER_SQLI = ./models/sql_inject/tokenizer.joblib
THRESHOLD_WARN_SCANN = ./models/scanning_models/ids_model.pkl
SCALER_FILE_SCANN = ./models/scanning_models/ids_scaler.pkl


[ai]
AI_THRESHOLD = 0.60
BEH_THRESHOLD = 0.80
SOC_AI_PROB_LIMIT = 0.3
BEHAVIOR_THRESHOLD = 0.60
MODEL_FILE = model.joblib
USE_SOC_AI = True
SOC_AI_MODEL = llama3:8b
MAX_LEN_SQLI = 120
THRESHOLD_BLOCK_SQLI = 0.85
THRESHOLD_WARN_SQLI  = 0.60

AI_THRESHOLD_ATTACK = 0.8
AI_THRESHOLD_SUSPICIOUS = 0.6
WINDOW_SECONDS = 3

DEBUG_PAYLOAD = False


[port_scann]
SCAN_WINDOW = 5
SCAN_THRESHOLD = 10

PORT_SCAN_PORTS_THRESHOLD = 5
PORT_SCAN_SYN_THRESHOLD = 20
PORT_SCAN_FLOWS_THRESHOLD = 15
PACKET_SAMPLE_RATE = 3 

#WINDOW_SECONDS = 3
#PORT_SCAN_PORTS_THRESHOLD = 20
#PORT_SCAN_SYN_THRESHOLD = 30
#PORT_SCAN_FLOWS_THRESHOLD = 25

[dedup]
DEDUP_WINDOW = 10

[color]
RED = \033[91m
GREEN = \033[92m
YELLOW = \033[93m
BLUE = \033[94m
CYAN = \033[96m
MAGENTA = \033[95m
WHITE = \033[97m
RESET = \033[0m
PURPLE = \033[35m
BG_RED = \033[41m

[line_color]
YELLOW_BG = \033[93m

[text_style]
BOLD = "\033[1m"
DIM = "\033[2m"
UNDERLINE = "\033[4m"
BLINK = "\033[5m"
REVERSE = "\033[7m"

[config_file]
status_file="./config/status.conf"
suricata_conf = "/etc/suricata/suricata.yaml"
log_dir = "suricata_out"
source="../detectionAI/venv"






