[network]
wlan0 = connected
vethe678b41 = connected
veth098d59f = connected
veth0472153 = connected
vboxnet0 = connected
lo = disconnected
eth0 = disconnected
docker0 = disconnected
br-06a6878c9871 = connected

[icons]
wlan0 = 📡
vethe678b41 = 🔗
veth098d59f = 🔗
veth0472153 = 🔗
vboxnet0 = 🌐
lo = 🖥️ 
eth0 = 🖧 
docker0 = 🐳
br-06a6878c9871 = 🌐

[networks-id]

[service]
SuricataProcess = False
SuricataService = False
